name: 'AEM Forms Performance Analyzer'
description: 'Analyzes AEM Adaptive Forms performance: API calls, rule cycles, hidden fields, CSS issues, and custom function violations.'
author: 'rismehta'

branding:
  icon: 'activity'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}

runs:
  using: 'node20'
  main: 'src/index.js'

