name: 'Performance Bot'
description: 'Analyzes form performance by comparing before/after URLs in pull requests'
author: 'rismehta'

branding:
  icon: 'activity'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}

runs:
  using: 'node20'
  main: 'src/index.js'

