name: 'AEM Forms Performance Analyzer'
description: 'Analyzes Adobe Experience Manager (AEM) Adaptive Forms performance by comparing before/after URLs in pull requests. Detects API calls in initialize, hidden field bloat, rule cycles, custom function violations, and CSS issues.'
author: 'rismehta'

branding:
  icon: 'activity'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}

runs:
  using: 'node20'
  main: 'src/index.js'

